### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by SteveLasker** [datatrails/datatrails-docs#672]
Within the docs, we refer to https://app.rkvst.io/ as the "app", "portal", "UI", and "dashboard"

Updates to the contributing & styles docs (#671) are helping with the consistency. 
What do we want to actually use?

cc: @beekman33

**Comment by JAG-UK** [comment]
Portal and dashboard are definitely wrong. 

The choice of 'app' or 'UI' should be context dependent. Generally it should be 'UI' as that contrasts better with the alternatives of 'API' or 'Python', and it's hard to say we really have an 'app'.

**Comment by SteveLasker** [comment]
TODO: update #671 to include terminology references.

**Comment by SteveLasker** [comment]
Going with `App` in PR #669. Might want to review to see how it looks

**Comment by pcnorth** [comment]
I tend to use UI for app.rkvst.io
If I use "portal" I'm most likely to be talking about the Zendesk Support portal knowledgebase.
