### ISSUE TITLE
Search widget has text truncated

### ISSUE THREAD

**Issue by j-hartley** [datatrails/datatrails-docs#72]
## Description

Search box has text truncated "Search do"

### Steps to reproduce

https://docs.jitsuin.com/docs/overview/introduction/

Look at the search box in the head banner

### Expected result

I expect to see the text "Search docs"

### Actual result

I see the text "Search do"

![Screenshot 2021-07-22 at 18 11 37](https://user-images.githubusercontent.com/41830007/126680808-ae0159dd-0aa9-4243-8cea-018594185655.png)

### Environment

Safari Version 14.1.1 (16611.2.7.1.4)

**Comment by leflambeur** [comment]
Hey @j-hartley - thanks for pointing this out

I'm planning a PR to be delivered next week to finish some of the dependencies on upgrading the search bar

Once that is done I'll follow up to verify if this is fixed or not 😃

**Comment by kjc-datatrails** [comment]
no longer present
